name: Build RPM Package

on:
  push:
    branches:
      - main
    paths:
      - 'rpm/.spec'
      - '.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: centos:8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure YUM to use vault.centos.org
        run: |
          sed -i 's|mirrorlist=http://mirrorlist.centos.org|#mirrorlist=http://mirrorlist.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo

      - name: Install RPM build tools
        run: |
          yum install -y rpm-build rpmdevtools wget unzip
          rpmdev-setuptree

      - name: Build RPM
        run: |
          cp rpm/calcfiles.spec ~/rpmbuild/SPECS/
          cd ~/rpmbuild/SOURCES/
          wget https://github.com/Maxrule/System-Programming/archive/main.zip
          unzip -o main.zip  # Распакуйте ZIP здесь
          sed -i 's/\r$//g' System-Programming-main/calcfiless.sh  # Удаляем ^M из скрипта
          mv System-Programming-main/* ./  # Перемещаем файлы
          rm -rf System-Programming-main  # Удаляем директорию
          cd ../../
          rpmbuild -bs --define "dist .generic" rpmbuild/SPECS/calcfiles.spec
          rpmbuild --rebuild rpmbuild/SRPMS/calcfiles-1.0-1.generic.src.rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v3
        with:
          name: rpm-package
          path: |
            ~/rpmbuild/RPMS/noarch/*.rpm
            ~/rpmbuild/SRPMS/*.src.rpm
